name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
          
    - name: Generate synthetic data
      run: |
        source venv/bin/activate
        python scripts/generate_synthetic_data.py

    - name: Train the model
      run: |
        source venv/bin/activate
        python src/train_model.py

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest